"""typo

Revision ID: 34cd4f343641
Revises: 2a64390486ce
Create Date: 2018-09-05 11:07:44.201381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34cd4f343641'
down_revision = '2a64390486ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('flag_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_score_flag_count'), 'score', ['flag_count'], unique=False)
    op.drop_index('ix_score_falg_count', table_name='score')
    op.drop_column('score', 'falg_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('falg_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_score_falg_count', 'score', ['falg_count'], unique=False)
    op.drop_index(op.f('ix_score_flag_count'), table_name='score')
    op.drop_column('score', 'flag_count')
    # ### end Alembic commands ###
