"""Create database

Revision ID: 5bcf73b1f5f3
Revises: 
Create Date: 2019-09-14 21:31:52.526220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcf73b1f5f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_rank',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('custom_message', sa.String(length=500), nullable=False),
    sa.Column('flag_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('custom_rank')
    # ### end Alembic commands ###
